% This is a script that handles the input parameters for doing particle locating using the Kilfoil location software on deconvolved images. It takes a hashvalue and a lot unnecessary comments have been stripped to make the code more readable there is no bandpass filtering Kate Jensen - cleaned up and prepared for distribution January 28, 2013 Modifications to interface with hashing and deconvolution on oddyysey Zsolt Jan 14 2019
addpath ~/Matlab/ 										%odyssey
image_filename = 't0000_rb150px_gelStackZ113.tif';
display(['Image file ' image_filename ' will be used.'])
output_filename = strcat(image_filename(1:length(image_filename)-4),'_coordinates.xyz');
lnoise = [0.9 0.9 0.7]; 									% not used since no bpass filtered will be applied
lobject = [27 27 27]; 										% not used since no bpass filtered will be applied

diameters = [35 35 35]; 									%numbers somewhat larger than the largest particle diameter I think diameters is used during llmx3dMB, ie local max finding routine
mask_size = [20 20 20]; 									%numbers somewhat smaller than the smallest particle diameter: % I think that mask_size is used to calculate properties such as total % intensity over the mask size area...with some potentially significant % effects of rounding and pixelation due to extensive use of floor(*) % functions. -Zsolt Apr 2017 % mask_size also comes into play during fracShift, so perhaps it limits the % area over which you shift the particles. 
min_separation = [19 19 19]; 									%a minimum separation cutoff to help prevent doubly-located particles %(set conservatively; this is to avoid a single particle being detected twice) % This is a bit misleading variable name. Any local max that are closer % than min_separation will be *merged* and if the center of mass shift by % more than 1/2? pix the position is discarded...this really should be set close but less than a particle diameter.  
masscut_initial = 7e5; %3.5e4; 									%masscut parameters determined by looking at the histogram of masses; %"particles" having less integrated intensity than this cutoff will be ignored %adjusted based on a histogram of the masses; note that during iterations, the histogram %has a long tail due to particle near the edges of the sample, but only the highest %"mass" particles are real
masscut_residuals = 1e5;
false_particle_size = [29 29 29]; 								%for creating residual images, define the extent of the virtual particle %that will be used to remove already-found particles from the image data: %(these should be odd integers; if not, the software will automatically %round up to the nearest odd integer)
bridgeThreshold = 0.5; 										% use threshold as described in the Kilfoil's comments on feature3dMB to % remove pixel biasing due to faint bridges between particles % value should be less than 1 % This applies a local (elliposoidal region within diameter) threshold on % the intensity to improve subpixel accuracy. 
zeroPxThreshold =200; 										% New parameter added to prevent erroneous locations during iterative % particle locating.  % This parameter places threshold on the number of identitically zero pixels % that can be part of the local max region. The threshold is applied before % shift the locations to the center % The proper choice should be correlated with the size of the object and % used in conjunction with masscut
